sudo: required
services:
- docker
language: python
<<<<<<< Updated upstream
=======
env:
  - SPEC_RELEASE_URL=https://github.com/kbase/relation_engine_spec/archive/v0.0.2.tar.gz
>>>>>>> Stashed changes
python:
- 3.6
script:
- cp .env.example .env
- docker-compose up -d
- make test
