version: '3'

# This docker-compose is for developer convenience, not for running in production.

services:

  # For running the Flask server
  web:
    build:
      context: .
      args:
        DEVELOPMENT: 1
    ports:
      - 5000:5000
    volumes:
      - ${PWD}:/app
    environment:
      - KBASE_AUTH_URL=http://auth:5000
      - PYTHONUNBUFFERED=true
      - DB_URL=http://arangodb:8529
      - DB_USER=root
      - DB_PASS=password
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  # For running (and testing against) ArangoDB
  arangodb:
    image: arangodb:3.3.19
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=password

  # A mock kbase auth server (see src/test/mock_auth/endpoints.json)
  auth:
    image: mockservices/mock_json_service
    volumes:
      - ${PWD}/src/test/mock_auth:/config
