version: '3'

# This docker-compose is for developer convenience, not for running in production.

services:

  # For running the Flask server
  web:
    build:
      context: .
      args:
        DEVELOPMENT: 1
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=true
      - DB_URL=http://arangodb:8529
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  # For running (and testing against) ArangoDB
  arangodb:
    image: arangodb
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=password
