version: '3'

services:

  # For running the Flask server
  web:
    build: .
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=true
      - DB_URL=http://arangodb:8529

  # For running (and testing against) ArangoDB
  arangodb:
    image: arangodb
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=password
