name: Relation Engine test and deploy
on:
  [push, pull_request]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout git repo
      uses: actions/checkout@v2

    - name: run tests
      shell: bash
      env:
        GITHUB_ACTIONS_CI: 1
      run: |
        docker-compose build
        docker-compose run re_api sh scripts/run_tests.sh
        docker-compose down --remove-orphans

  docker_build_and_push:
    runs-on: ubuntu-latest
    needs: run_tests
    if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') && github.event_name == 'push' && !contains(github.event.head_commit.message, 'skip_docker_build')
    steps:
    - name: checkout git repo
      uses: actions/checkout@v2

    - name: copy VERSION to TAG_NAME
      shell: bash
      run: |
        mkdir -p .target
        cp VERSION .target/TAG_NAME

    - name: set env vars
      shell: bash
      run: |
        echo ::set-env name=DATE::$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        echo ::set-env name=BRANCH::$(git symbolic-ref --short HEAD)
        echo ::set-env name=COMMIT::$(git rev-parse --short HEAD)

    - name: build and push to dockerhub
      uses: opspresso/action-docker@master
      with:
        args: --docker
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERFILE: "Dockerfile"
        IMAGE_NAME: "kbase/relation_engine_api"
