name: Run Tests
on:
  [push, pull_request]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout git repo
      uses: actions/checkout@v2

    - name: run tests
      shell: bash
      env:
        GITHUB_ACTIONS_CI: 1
      run: |
        docker-compose build
        docker-compose run re_api sh scripts/run_tests.sh
        docker-compose down --remove-orphans
